### ISSUE TITLE
Release checklist

### ISSUE THREAD

**Issue by shorowit** [NREL/OpenStudio-HPXML#304]
- [ ] Bump version
- [ ] Create release zip files
- [ ] Create release w/ release notes
- [ ] Make release documentation public
