### ISSUE TITLE
OS 3.1/EP 9.4 Checklist

### ISSUE THREAD

**Issue by shorowit** [NREL/OpenStudio-HPXML#461]
- [x] Remove `require 'openstudio'` from all scripts (in this repo and others) due to [lazy loading](https://github.com/NREL/OpenStudio/pull/4028)
- [x] [Allow coal for non-boiler heating systems](https://github.com/NREL/OpenStudio-HPXML/pull/439)
- [x] [Improve window shading multipliers](https://github.com/NREL/OpenStudio-HPXML/pull/296)
- [x] [Add interior surface test](https://github.com/NREL/OpenStudio-HPXML/pull/454)
- [x] [Update FuelOil references as needed](https://github.com/NREL/EnergyPlus/pull/8134)
- [x] Double-check [E+ DST bugfix](https://github.com/NREL/EnergyPlus/pull/8118)
- [x] Double-check [E+ simple window model bugfix](https://github.com/NREL/EnergyPlus/pull/8001)
- [x] Remove [E+ Kiva warning exception](https://github.com/NREL/EnergyPlus/pull/8073)
- [x] Remove [E+ stratified tank warning exception](https://github.com/NREL/EnergyPlus/pull/8172)
- [x] Remove [OS propane warning exception](https://github.com/NREL/OpenStudio/pull/3999)
- [x] Try new OutputControl:Files object
